import assets from "./assets";

export const products = [
	{
		id: "1",
		title: "Apple iPhone 13, 128GB, White - Unlocked ",
		price: 899.95,
		category: "electronics",
		image: assets.item01,
	},
	{
		id: "2",
		title: "Apple 2021 MacBook Pro (16-inch, 32GB RAM, 512GB SSD) - Space Gray Z14V0",
		price: 2200.0,
		category: "electronics",
		image: assets.item02,
	},
	{
		id: "3",
		title: "Canon EOS Rebel T7 DSLR Camera with 18-55mm Lens | Built-in Wi-Fi | 24.1 MP CMOS Sensor | DIGIC 4+ Image Processor and Full HD Videos",
		price: 550.99,
		category: "electronics",
		image: assets.item03,
	},
	{
		id: "4",
		title: "Alternative Trap Mixtape: An innovative project by Lucki Eck$",
		price: 39.99,
		category: "music",
		image: assets.item04,
	},
	{
		id: "5",
		title: "Designer Backpacks for Men",
		price: 695,
		category: "men's clothing",
		image: assets.item05,
	},
	{
		id: "6",
		title: "Nike Air Force 1 Mid x Off-White",
		price: 495,
		category: "shoes",
		image: assets.item06,
	},
	{
		id: "7",
		title: "CDG BIG Red Heart Hoodie",
		price: 299.99,
		category: "men's clothing",
		image: assets.item07,
	},
	{
		id: "8",
		title: "Flawless Like Me - Pink & White Galaxy: CDs & Vinyl",
		price: 49.99,
		category: "music",
		image: assets.item08,
	},
	{
		id: "9",
		title: "Flawless RSB Hoodie",
		price: 110,
		category: "men's clothing",
		image: assets.item09,
	},
	{
		id: "10",
		title: "TEDDYBEAR BACKPACK",
		price: 80.0,
		category: "men's clothing",
		image: assets.item10,
	},
	{
		id: "11",
		title: "Flawless UGK Hoodie",
		price: 105,
		category: "men's clothing",
		image: assets.item11,
	},
	{
		id: "12",
		title: "CDG Play Red Heart Hoodie",
		price: 299.99,
		category: "men's clothing",
		image: assets.item12,
	},
	{
		id: "13",
		title: "Nike Air Force 1 '07 (Classic)",
		price: 99,
		category: "shoes",
		image: assets.item13,
	},
	{
		id: "14",
		title: "Nike Air Force 1 '07 (Just Do It)",
		price: 199.99,
		category: "shoes",
		image: assets.item14,
	},
	{
		id: "15",
		title: "Nike Air Force 1 '07 (FLEA)",
		price: 156.99,
		category: "shoes",
		image: assets.item15,
	},
	{
		id: "16",
		title: "Lock and Love Nike Air Force",
		price: 89.95,
		category: "women's clothing",
		image: assets.item16,
	},
	{
		id: "17",
		title: "THRASHER Hoodie",
		price: 399.99,
		category: "men's clothing",
		image: assets.item17,
	},
	{
		id: "18",
		title: "Black Lives Matter Hoodie",
		price: 79.85,
		category: "men's clothing",
		image: assets.item18,
	},
	{
		id: "19",
		title: "Crop Sweater",
		price: 77.95,
		category: "women's clothing",
		image: assets.item19,
	},
	{
		id: "20",
		title: "XXXTENTACION Hoodie",
		price: 122.99,
		category: "men's clothing",
		image: assets.item20,
	},
];
